### ISSUE TITLE
Procedural High Explosive detonating too early,

### ISSUE THREAD

**Issue by C1etus** [jrodrigv/BDModularMissileParts#11]
Just downloaded this and have been trying to make bombs with the new Procedural High Explosive part, as well as using the Missile Core part. Anytime I fire my bomb from the BDArmory Menu, the bomb explodes within seconds. I've tried enabling, disabling, and turning the detonation distance override to 0, and nothing has worked. If you know a fix that would be greatly appreciated.

**Comment by jrodrigv** [comment]
I believe the problem that you are experiencing with your missile is that is does not have a target locked. Missiles without target will auto destroy within seconds

**Comment by C1etus** [comment]
The bombs im using tho are gps guided, and I do set the targets on the missile core before even flying

**Comment by jrodrigv** [comment]
My procedural missile core didn't support gps guidance so maybe you are a different Bdarmory version like the Runway Project version?

**Comment by C1etus** [comment]
Even when using the procedural high explosive and the modular missile part that comes w/ bdarmory, it doesnt work neither

**Comment by C1etus** [comment]
FIXED: I WAS USING JET ENGINES

Apparently jet engines do not work well with the GPS guidance system, however the RAPIER air breathing mode seems to work.. very strange/
