### ISSUE TITLE
parts not showing

### ISSUE THREAD

**Issue by Bluisharagarn** [jrodrigv/BDModularMissileParts#2]
the procedural missle parts are not showing up in my parts. as far as i know ive installed everything correctly.
using ksp 1.3 
mods used : 
bdarmory,
modularmissleparts and proceduralparts.
i have no clue what i am doing wrong
[output_log.txt](https://github.com/jrodrigv/BDModularMissileParts/files/1133017/output_log.txt)

edit forgot ksp version

**Comment by ghost** [comment]
It;s probaly because this hasen't been updated for awhile.

**Comment by jrodrigv** [comment]
Sorry for the delay. The parts pack is working fine in KSP 1.2.2 and KSP 1.3 IS as long as you have properly installed BDArmory latest version and Procedural Parts latest version. Can you provide a KSP.log

**Comment by Bluisharagarn** [comment]
i managed to fix it, no idea how but the parts are now showing :D this isea can be closed
