### ISSUE TITLE
Career mode is broken

### ISSUE THREAD

**Issue by AcidBurn9** [jrodrigv/BDModularMissileParts#6]
In career mode modular parts are broken.

https://imgur.com/gallery/HettwNg

In SPH/VAB parts dont change at all, but in flight they have shape and size you decide. And procedural explosive doesnt change explosive mass/radius at all (even in a flight)

In sandbox everything works.

KSP 1.7

**Comment by jrodrigv** [comment]
Sorry but this mod was not designed for career mod.
