### ISSUE TITLE
1.8?

### ISSUE THREAD

**Issue by The-Faulty** [jrodrigv/BDModularMissileParts#7]
Hi, I dont know if you are still looking at this, but I would love it if you could recompile this for 1.8, the parts are not showing up for me. Thanks!

**Comment by jrodrigv** [comment]
Dude...
BDArmory has not been released for KSP 1.8, and I'm not sure if procedural
parts is ready yet

**Comment by The-Faulty** [comment]
Well, the parts are there and working fine for the most part, but whenever I launch the vehicle and go back to the vab, the parts have separated and then dont have the proper mounting points and cant be reattached.

**Comment by jrodrigv** [comment]
Now everything is ready. If you review my github repos you will find BDArmory, ProceduralParts, B9 Procedural Wings and of course this mod :)
